# We upload two separate reports: js and java
codecov:
    notify:
        after_n_builds: 3
comment:
    after_n_builds: 3
coverage:
    status:
        project:
            default:
                threshold: 1.0
