name: Rosetta API

on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
			- uses: actions/checkout@v2
			- uses: actions/setup-go@v2
				with:
					go-version: '1.13'
			- run: 
  test:
    runs-on: ubuntu-latest
	code_coverage:
		runs-on: ubuntu-latest

