name: Rosetta API

on:
  - push

env:
    working-directory: ./hedera-mirror-rosetta
    code-cov-report: rosetta-code-cov-report
    image-tag: mirror-node

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.13'
      - run: go build -i -o rosetta cmd/*
        working-directory: ${{env.working-directory}}
      - uses: actions/upload-artifact@master
        with:
          name: hedera-mirror-rosetta
          path: ${{ env.working-directory }}/rosetta
          if-no-files-found: error
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.13'
      - run: go test ./... -race -coverprofile=coverage.txt -covermode=atomic
        working-directory: ${{env.working-directory}}
      - run: bash <(curl -s https://codecov.io/bash)
        working-directory: ${{env.working-directory}} 
  cli-validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Mirror Node
        run: docker build --tag=${{env.image-tag}} .
        working-directory: ${{env.working-directory}}/build
      - name: Run Mirror Node
        run: docker run -d ${{env.image-tag}} -p 5700:5700
      - name: Wait for Mirror Node to start (60s)
        run: sleep 60
      - name: Run CLI Validation
        run: bash ./validation/run-validation.sh
        working-directory: ${{env.working-directory}}
    