name: Rosetta Validation

on: 
  - push

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Run Rosetta Mirror Node
      run: docker-compose up --build -d

    - name: Wait for Mirror Node to start
      run: bash ./.github/workflows/wait-for-mirror-node.sh

    - name: Run CLI Validation
      run: bash ./hedera-mirror-rosetta/run-validation.sh
