name: Rosetta API

on:
  - push

env:
    working-directory: ./hedera-mirror-rosetta

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.13'
      - run: go build -i -o rosetta cmd/*
        working-directory: ${{env.working-directory}}
      - uses: actions/upload-artifact@master
        working-directory: ${{env.working-directory}}
        with:
          name: hedera-mirror-rosetta
          path: rosetta
